### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by romulogoncalves** [FernLab/cookiecutter-py-package#3]
Update the current README to better inform the users and say it is a fork from [audreyfeldroy/cookiecutter-pypackage](https://github.com/audreyfeldroy/cookiecutter-pypackage)

**Comment by DaRa42** [comment]
- [ ] update README in main folder
- [ ] update files in main /docs to the fernlab version and link to the original

**Comment by DaRa42** [comment]
see pull request #5
