### ISSUE TITLE
FERN.Lab logo is not shown correctly in README

### ISSUE THREAD

**Issue by danschef** [FernLab/cookiecutter-py-package#7]
There is just a white space, no logo is shown:

![grafik](https://github.com/user-attachments/assets/6868d37a-79c4-4662-ac6f-5fd0bb1da3ab)

It may also be nicer to put the FernLab_Logo.svg to the docs directory instead of having it in the package root directory.

**Comment by romulogoncalves** [comment]
@danschef if you use the black mode you can see it. Should we place the image for white mode since it is the default one?
@DaRa42 what do you think?

**Comment by DaRa42** [comment]
@romulogoncalves yes I would go for white mode as default and adapt the image for it

**Comment by romulogoncalves** [comment]
@DaRa42 is this solved by #5 ?

**Comment by DaRa42** [comment]
I will test it

**Comment by DaRa42** [comment]
![image](https://github.com/user-attachments/assets/a941a21e-f61e-4471-b11d-474a93e7fa6f)

No it seems not

**Comment by romulogoncalves** [comment]
It should be fixed by:
https://github.com/FernLab/cookiecutter-py-package/commit/2d77b69cd1965146e7379a4b67cc4a11f264f2a8
